
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
usb:
history:
powercalc:

# Text to speech
tts:
  - platform: google_translate

birthdays: !include birthdays.yaml

http:
    ip_ban_enabled: true
    login_attempts_threshold: 5

logger:
  default: info
  logs:
    custom_components.robovac.vacuum: debug
    custom_components.robovac.tuyalocalapi: debug
    homeassistant.core: debug

counter:
  robovac_usage:
    initial: 0
    step: 1

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Dirty
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle    
  tumbledryer_status:
    name: Tumbledryer Status
    options:
      - Idle
      - Tumbling
      - Drying
      - Finished
  home_mode_status:
    name: Home Mode
    options:
      - Away
      - Normal
      - Bed time
      - Alarmed
      - Alone
  voice_announcements_status:
    name: Voice Status
    options:
      - Disabled
      - Enabled
input_text:
  ensuite_button_helper:
    name: 'Ensuite Button Helper'
recorder:
  commit_interval: 5
sensor:
  - platform: history_stats
    name: Ken Meeting Duration
    entity_id: binary_sensor.TRAMEXKWG_meeting 
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
    unique_id: history_ken_meeting_duration
  - platform: history_stats
    name: Aisling Meeting Duration
    entity_id: input_boolean.aisling_meeting
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
    unique_id: history_aisling_meeting_duration
  - platform: integration
    name: dishwasher_energy_spent
    source: sensor.switchdishwasher_smartenergy_metering
    unit_prefix: k
    round: 2
    unique_id: dishwasher_energy_spent
  - platform: integration
    name: tumble_dryer_energy_spent
    source: sensor.plugtumble_dryer_smartenergy_metering
    unit_prefix: k
    round: 2
    unique_id: tumble_dryer_energy_spent
  - platform: integration
    name: washing_machine_energy_spent
    source: sensor.plugwashing_machine_smartenergy_metering
    unit_prefix: k
    round: 2
    unique_id: washing_machine_energy_spent
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'
      tumbledryer_status:
        value_template: '{{states.input_select.tumbledryer_status.state}}'
        friendly_name: 'Tumbledryer Status'
      kens_alarm:
        value_template: '{{now().strftime("%a %h %d %H:%M %Z %Y") == (((state_attr("sensor.kens_phone_next_alarm", "Time in Milliseconds") | int / 1000)) | timestamp_custom("%a %h %d %H:%M %Z %Y"))}}'
        friendly_name: 'Ken''s Alarm'
  - platform: time_date
    display_options:
      - "time"
      - "date"

command_line:
  - binary_sensor:
      name: CPU Temperature
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      value_template: '{{ value | multiply(0.001) }}'


notify:
  - name: notify_via_pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

# Example configuration.yaml entry
binary_sensor:
#  - platform: uptimerobot
#    api_key: !secret uptimerobot_api_key
#  - platform: workday
#    country: IE
#    add_holidays:
#      - '2022-10-03'
#      - '2022-10-04'
#      - '2022-10-05'
#      - '2022-10-06'
#      - '2022-10-07'
#    remove_holidays:
#      - '2022-06-03'


# Create a group for referring to the kitchen lights at once
light:
  - platform: group
    name: Kitchen Lights
    entities:
    - light.front_kitchen_light
    - light.back_kitchen_light
  - platform: group
    name: Bedside Lamps
    entities:
    - light.lightaisling_level_light_color_on_off
    - light.lightken_level_light_color_on_off
  - platform: group
    name: All lights
    entities:
    - light.back_kitchen_light
    - light.cats_room
    - light.cloak_room
    - light.front_kitchen_light
    - light.hall_light
    - light.landing
    - light.laundry_room_light
    - light.living_room_light
    - light.study_light_level_on_off
    - light.top_landing_light
  - platform: group
    name: All downstairs lights
    entities:
    - light.front_kitchen_light
    - light.back_kitchen_light
    - light.cloak_room
    - light.hall_light
    - light.laundry_room_light

      
shell_command:
  grocy_consume_item: "curl -X POST http://{{server_ip}}:9192/api/stock/products/{{product_id}}/consume -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'GROCY-API-KEY: {{grocy_key}}' -H 'cache-control: no-cache' -d '{ \"amount\": {{amount}},  \"transaction_type\": \"consume\",  \"spoiled\": false }'"

frontend:
  themes: !include_dir_merge_named themes

climate:
  - platform: generic_thermostat
    name: Study
    heater: switch.heater_study
    target_sensor: sensor.study_weather_temperature
    cold_tolerance: 0
    hot_tolerance: 0

  - platform: generic_thermostat
    name: Guest Bedroom
    heater: switch.guestbedroom_heater
    target_sensor: sensor.guestbedroom_temperature
    cold_tolerance: 0
    hot_tolerance: 0.5

  - platform: generic_thermostat
    name: Master Bedroom
    heater: switch.heater_master_bedroom
    target_sensor: sensor.masterbedroom_temperature

group: !include groups.yaml

template:
  - trigger:
      platform: time_pattern
      minutes: "1"
      seconds: "1"
  - binary_sensor:
      name: "Christmas Time"
      state: >-
        {{ ((now().month == 12) or (now().month == 1 and now().day <= 6)) }} 

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml

wake_on_lan:
  - name: TramexKWG
    mac_address: 08-8F-C3-5A-C8-D7
    host: 192.168.178.47

switch:
  - platform: wake_on_lan
    mac: 08-8F-C3-5A-C8-D7
    name: "WakeTramexKWG"
    host: 192.168.178.47

zha:
  zigpy_config:
    ota:
      ikea_provider: true
