
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
usb:

# Text to speech
tts:
  - platform: google_translate
  
http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem
    ip_ban_enabled: true
    login_attempts_threshold: 5
    
hive:
  username: !secret hive_username
  password: !secret hive_password

eufy_vacuum:
  devices:
  - name: Robovac
    address: 192.168.178.32
    access_token: !secret robovac_token
    id: !secret robovac_id
    type: T2118

counter:
  robovac_usage:
    initial: 0
    step: 1

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Dirty
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle    
  tumbledryer_status:
    name: Tumbledryer Status
    options:
      - Idle
      - Tumbling
      - Drying
      - Finished
  home_mode_status:
    name: Home Mode
    options:
      - Away
      - Normal
      - Bed time
      - Alarmed
      - Alone
  voice_announcements_status:
    name: Voice Status
    options:
      - Disabled
      - Enabled
input_text:
  ensuite_button_helper:
    name: 'Ensuite Button Helper'
recorder:
  commit_interval: 5
sensor:
  - platform: dnsip
    name: external_ip
  - platform: integration
    name: dishwasher_energy_spent
    source: sensor.switchdishwasher_smartenergy_metering
    unit_prefix: k
    round: 2
  - platform: integration
    name: tumble_dryer_energy_spent
    source: sensor.plugtumble_dryer_smartenergy_metering
    unit_prefix: k
    round: 2
  - platform: integration
    name: washing_machine_energy_spent
    source: sensor.plugwashing_machine_smartenergy_metering
    unit_prefix: k
    round: 2
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    monitored_conditions:
      - body
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'
      tumbledryer_status:
        value_template: '{{states.input_select.tumbledryer_status.state}}'
        friendly_name: 'Tumbledryer Status'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: load_1m
      - type: load_5m
      - type: load_15m
  - platform: time_date
    display_options:
      - "time"
      - "date"
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'

notify:
  - name: notify_via_pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

# Example configuration.yaml entry
binary_sensor:
#  - platform: uptimerobot
#    api_key: !secret uptimerobot_api_key
  - platform: workday
    country: GB
    add_holidays:
      - '2022-01-03'
      - '2022-01-04'
      - '2022-01-05'
      - '2022-01-06'
      - '2022-02-07'
      - '2022-02-08'
      - '2022-02-09'
      - '2022-02-10'
      - '2022-02-11'
      - '2022-03-17'
      - '2022-06-06'
    remove_holidays:
      - '2022-06-03'

  - platform: ping
    name: Chromecast
    host: 192.168.178.20
  - platform: ping
    name: Radagast
    host: 192.168.178.23
  - platform: ping
    name: Aisling's Chromebook
    host: 192.168.178.24
  - platform: ping
    name: Work Laptop
    host: 192.168.178.25
  - platform: ping
    name: TP-Link Repeater
    host: 192.168.178.26
  - platform: ping
    name: Printer
    host: 192.168.178.28
  - platform: ping
    name: Doorbell
    host: 192.168.178.29
  - platform: ping
    name: robovac
    host: 192.168.178.32
  - platform: ping
    name: Aisling's work laptop
    host: 192.168.178.33
  - platform: ping
    name: AJAXHub
    host: 192.168.178.34
  - platform: ping
    name: Aiwendil
    host: 192.168.178.35
  - platform: ping
    name: KitchenCam
    host: 192.168.178.40

# Create a group for referring to the kitchen lights at once
light:
  - platform: group
    name: Kitchen Lights
    entities:
    - light.front_kitchen_light
    - light.back_kitchen_light
  - platform: group
    name: Bedside Lamps
    entities:
    - light.lightaisling_level_light_color_on_off
    - light.lightken_level_light_color_on_off
  - platform: group
    name: All lights
    entities:
    - light.back_kitchen_light
    - light.cats_room
    - light.cloak_room
    - light.front_kitchen_light
    - light.guest_room
    - light.hall_light
    - light.landing
    - light.laundry_room_light
    - light.living_room_light
    - light.study_light_level_on_off
    - light.top_landing_light

      
shell_command:
  grocy_consume_item: "curl -X POST http://{{server_ip}}:9192/api/stock/products/{{product_id}}/consume -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'GROCY-API-KEY: {{grocy_key}}' -H 'cache-control: no-cache' -d '{ \"amount\": {{amount}},  \"transaction_type\": \"consume\",  \"spoiled\": false }'"

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
  
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml

zha:
  zigpy_config:
    ota:
      ikea_provider: true
